# Generated by Django 6.0.4 on 2026-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='indeficator',
            field=models.CharField(default='121212121212', max_length=100, unique=True, verbose_name='Индефикатор товара'),
        ),
    ]
