# Generated by Django 6.0.4 on 2026-06-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_indeficator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indeficator',
            field=models.CharField(max_length=100, unique=True, verbose_name='Индефикатор товара'),
        ),
    ]
